config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: :create
  end
  resources :bookmarks, only: :destroy
  resources :reviews, only: :destroy
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: 'is already in the list' }
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :picture_url, presence: true, allow_blank: true
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :comment, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_bookmark, only: :destroy
  before_action :find_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy

    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def find_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def find_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # frozen_string_literal: true
  before_action :find_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def show
    @bookmark = Bookmark.new
    @review = Review.new
  end

  def destroy
    @list.destroy

    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :picture_url, :photo)
  end

  def find_list
    @list = List.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_review, only: :destroy
  before_action :find_list, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render '../views/lists/show.html.erb'
    end
  end

  def destroy
    @review.destroy

    redirect_to list_path(@review.list)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end

  def find_review
    @review = Review.find(params[:id])
  end

  def find_list
    @list = List.find(params[:list_id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_new.html.erb
<div class="modal fade" id="new_movie_modal" role="dialog">
  <div class="modal-dialog modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add movie to your <%= @list.name %> list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Select a movie", input_html: {data: {controller: 'select2', select2_options_value: {tags: true}}} %>
          <%= f.input :comment %>
          <%= f.button :submit, "Add Movie", class: 'btn btn-primary'%>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/bookmarks/new.html.erb
<div class="p-5 mt-5 shadow bg-white rounded justify-content-center">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Select a movie", input_html: {data: {controller: 'select2', select2_options_value: {tags: true}}} %>
    <%= f.input :comment %>
    <%= f.button :submit, "Add Movie", class: 'btn btn-primary'%>
  <% end %>
  <%= link_to 'Back', lists_path, class: 'btn btn-primary mt-3' %>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to image_tag("http://cdn.onlinewebfonts.com/svg/img_503358.png"), lists_path, class: "navbar-brand" %>
    <%= link_to 'Create new list', new_list_path, class: "btn btn-outline-primary text-end" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>


  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="p-5 mt-5 shadow bg-white rounded justify-content-center">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.input :picture_url %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/index.html.erb
<div class="home-banner">
    <div class="typed-js" data-controller="typed-js"></div>
</div>

  <div class="cards-container">
    <% @lists.each do |list| %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=list.photo.attached? ? cl_image_path(list.photo.key) : list.picture_url%>)">
        <div class="list-name"><%= link_to list.name, list_path(list)%></div>
        <div class="icon-1"><%= link_to '<i class="fa-solid fa-xmark"></i>'.html_safe, list_path(list), method: :delete, data: { confirm: 'Are you sure?' }, class: "delete_list" %></div>
      </div>
          <% end %>
  </div>


</div>

app/views/lists/new.html.erb
<%= render 'form' %>

app/views/lists/show.html.erb
<div class="position-relative">
  <div class="card-category card-large" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : @list.picture_url %>)">
    <h1><%= @list.name %></h1>
  </div>
    <span class="movie-tag"><%= pluralize(@list.movies.size, 'movie') %></span>
</div>
<div class="p-5 mt-5 shadow bg-white rounded justify-content-center">
  <button type="button" class="text-end btn btn-primary" data-bs-toggle="modal" data-bs-target="#new_movie_modal">
        Add Movie
  </button>
  <%= render "bookmarks/new", list: @list %>
  <div class="row row-cols-1 row-cols-md-3 mt-3">
    <% @list.bookmarks.each do |bookmark| %>
    <div class="col-md-4 mb-4">
      <div class="shadow card h-100 img-thumbnail mb-2" style="">
        <img class="card-img img-thumbnail" src="<%=bookmark.movie.poster_url%>">
        <div class="card-body">
        <h4 class="fw-bolder"><%= bookmark.movie.title %></h4><h5 class="fw-light"><%= bookmark.movie.rating %> ⭐️</h5>
        <p class="card-text fw-lighter"><%= bookmark.movie.overview %></p>
        <hr>
        <small><em class="text-muted">Review:<br><%= bookmark.comment %></em></small>
        </div>
        <%= link_to 'Remove', bookmark_path(bookmark), method: :delete, data: { confirm: 'Are you sure?' }, class: "remove-button" %>
      </div>
    </div>
    <% end %>
  </div>

  <hr class="my-5">

  <div class="row">
    <div class="shadow p-5 col-12 col-sm-6">
      <h3>Reviews</h3>
      <% @list.reviews.each do |review| %>
        <div>
        <p><%= '⭐️' * review.rating %></p>
          <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
          <p class="mb-0"><%= review.comment %></p>
        </div>
        <hr>
      <% end %>
    </div>
    <div class="col-12 col-sm-6">
      <div class="bg-white rounded p-3">
      <h5>Add your review</h5>
      <%= simple_form_for [@list, @review] do |f| %>
        <%= f.input :comment, placeholder: "Add your review here..." %>
        <%= f.input :rating, as: :select, collection: (1..5), required: true, prompt: "What's your rating", input_html: { data: { controller: "jquery-bar-rating" } } %>
        <%= f.submit class:"btn btn-success" %>
      <% end %>
      </div>
    </div>
  </div>
  <%= link_to 'Back', lists_path, class: 'btn btn-primary mt-3' %>
</div>

app/views/reviews/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "http://cdn.onlinewebfonts.com/svg/img_503358.png" %>
    <% end %>

    <div class="btn-group dropstart me-1">
          <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">PRESS</button>
      <ul class="dropdown-menu ">
        <%= link_to 'Add List', new_list_path, class: "dropdown-item" %>
        <%= link_to 'My Lists', lists_path, class: "dropdown-item" %>
      </ul>
    </div>
  </div>
</div>